# GENERATE TIME: Thu Dec  7 10:20:34 2023
# CMD:
# .\train.py -opt C:\Users\Kim\Downloads\neosr-master\options\train_span.yml --auto_resume


name: train_span
model_type: default
scale: 4
num_gpu: 1
use_amp: true
bfloat16: true
compile: false
#manual_seed: 1024

datasets:
  train:
    type: paired
    dataroot_gt: 'I:\Dataset\UltraSharpV2\hr'
    dataroot_lq: 'I:\Dataset\UltraSharpV2\lr'
    meta_info: 'C:\Users\Kim\Downloads\neosr-master\dataset\util\output.txt'
    io_backend:
      type: disk

    gt_size: 128
    batch_size: 12
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 6
    dataset_enlarge_ratio: 5

path:
  pretrain_network_g: 'C:\Users\Kim\Downloads\neosr-master\experiments\train_span_archived_20231207_085720\models\net_g_75000.pth'
  #param_key_g: ~
  #strict_load_g: false
  #resume_state: 'C:\Users\Kim\Downloads\neosr-master\experiments\train_span\training_states\14000.state'

network_g:
  type: span

network_d:
  type: unet

train:
  optim_g:
    type: adamw
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: adamw
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: multisteplr
    milestones: [60000, 120000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: HuberLoss
    loss_weight: 1.0
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    perceptual_weight: 2
    style_weight: 0
    criterion: huber
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    loss_weight: 0.05
  color_opt:
    type: colorloss
    loss_weight: 2.5
    criterion: huber
  #ldl_opt:
  #  type: HuberLoss
  #  loss_weight: 1.0
  #  reduction: mean
  #ff_opt:
  #  type: focalfrequencyloss
  #  loss_weight: 0.5

logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  use_tb_logger: true
  #wandb:
  #  project: ~
  #  resume_id: ~

# dist training settings
#dist_params:
#  backend: nccl
#  port: 29500
